fix #7: add support for specializations
WoozyMasta/archimate-ci-image pull request #8
Opened 2022-09-19 08:12 UTC by Damounet

Fix the #7 

Like described in the comment of the issue, I installed yq that will allow the correct retrieval of the name of the archimate model without the specialization ones.

2022-09-19 08:52 UTC, Damounet commented
it seems the yq binary is not in atp, I'll have a look into it and fix this

2022-09-20 06:55 UTC, Damounet commented
@WoozyMasta It seems that the binary for archimate is not accessible anymore for this version, so I am unable to rebuild the image and test this properly.

Could you have a look into it and see if you can upgrade the version as well?

2022-09-20 08:05 UTC, Damounet commented
I tested the image localy, by downloading the current version, doing the modification in the container and testing it.

From my point of view, it's all fine, but you still need to bump the version archimate to rebuild a proper image I think.

2022-09-20 08:06 UTC, Damounet commented
closes #7

2022-10-28 12:13 UTC, Damounet commented
Hey @WoozyMasta , I am not sure you saw this PR or if you lack time working on the subject so I ping you :)

2022-10-28 15:51 UTC, joshliberty requested changes

2022-10-28 15:51 UTC, joshliberty commented on Dockerfile
> +    curl -O https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_darwin_amd64 -output /usr/bin/yq &&\
@Damounet the dockerfile uses ubuntu, Darwin is mac os - yq won't run

2023-05-09 12:11 UTC, kokeksibir commented
Lookslike @WoozyMasta is not maintaining this repository anymore. @Damounet it would be very nice of you if you can publish your docker image in docker or quay.

2023-05-09 13:34 UTC, merged